oxpus_meeting_controller:
    path: /meeting/
    defaults: { _controller: oxpus.meeting.controller:handle }
oxpus_meeting_page_controller:
    path: /meeting/
    defaults: { _controller: oxpus.meeting.controller:handle }
